#!/bin/sh
# Run this as the "Build Command" on your static hosting provider (Render
# Static Site, Netlify, Vercel, etc.), with API_BASE_URL set as an
# environment variable on that service pointing at your deployed backend.
#
# It's deliberately a plain shell script, not a Node build step — these
# are static files with no bundler involved, so nothing else needs to run
# before publishing.
set -e
: "${API_BASE_URL:?Set API_BASE_URL to your backend's public URL before building, e.g. https://affordmatch-api.onrender.com}"

cat > shared/config.js << EOF
// Generated by generate-config.sh at build time — do not edit directly.
window.AFFORDMATCH_API_BASE = "${API_BASE_URL}";
EOF

echo "Wrote shared/config.js -> AFFORDMATCH_API_BASE=${API_BASE_URL}"
